version: "2.1"

services:
  # -------------------- NeighbourStorage APIs Express Container -------------------- #

  Backend-server:
    image: coolgopalgoyal/majorprojectbackend:latest
    container_name: backend-server
    environment:
      - MYSQL_HOST=dbserver
      - MYSQL_PORT=3306
      - MYSQL_USER=root
    ports:
       - "8081:8081"
    depends_on:
      dbserver:
         condition: service_healthy
#     entrypoint: wait-for-it.sh dbserver:3306 -- echo "dbserver is up"

    networks:
      - backendmysql
    restart: unless-stopped

  # -------------------- MySqlDB -------------------- #

  dbserver:
    image: mysql/mysql-server:latest
    container_name: dbserver
    environment:
      - MYSQL_DATABASE=SpeMajordb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3308:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10  
    volumes:
      - /home/gopal/Desktop/temp/db:/var/lib/mysql
    networks:
      - backendmysql
    restart: unless-stopped

networks:
  backendmysql:
    driver: bridge

volumes:
  mysql-data:
    driver: local
