version: "3"

services:
  # -------------------- NeighbourStorage APIs Express Container -------------------- #

  Frontend-server:
    image: coolgopalgoyal/majorprojectfrontend
#    image: demo:latest
    container_name: frontend-server
    environment:
      - REACT_APP_API_URL=172.21.0.3
    ports:
      - "8100:8100"
    depends_on:
      - Backend-server
    networks:
      - backendmysql
    restart: unless-stopped

  Backend-server:
    #image: coolgopalgoyal/majorprojectbackend:latest
    image: coolgopalgoyal/logstashtesting:latest
    container_name: backend-server
    environment:
      - MYSQL_HOST=dbserver
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - LS_JAVA_OPTS="-Xmx256m -Xms256m"
    ports:
       - "8081:8081"
       - '9600:9600'
    depends_on:
       - dbserver
       - Elasticsearch
    command: logstash -f /logstash.conf
    volumes:
      - /home/gopal/Desktop/SpeMajor-backend/logfile:/logs
      - ./logstash/:/logstash_dir
    networks:
      - backendmysql
    restart: unless-stopped

  # -------------------- MySqlDB -------------------- #

  dbserver:
    image: mysql/mysql-server:latest
    container_name: dbserver
    environment:
      - MYSQL_DATABASE=SpeMajordb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "3308:3306"
    volumes:
      - /home/gopal/Desktop/SpeMajor-backend/backupdata:/var/lib/mysql
    networks:
      - backendmysql
    restart: unless-stopped

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/var/lib/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'

    networks:
      - backendmysql


  Kibana:
      image: kibana:7.16.2
      container_name: kibana
      restart: always
      ports:
        - '5601:5601'
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
        - Elasticsearch
      networks:
        - backendmysql

networks:
  backendmysql:
    driver: bridge

volumes:
  backupdata:
  logfile:
  elastic_data:
