version: "3"

services:
  # -------------------- NeighbourStorage APIs Express Container -------------------- #

  Backend-server:
    image: coolgopalgoyal/majorprojectbackend:latest
    container_name: backend-server
    environment:
      - MYSQL_HOST=dbserver
      - MYSQL_PORT=3306
      - MYSQL_USER=root
    ports:
       - "8081:8081"
    depends_on:
       - dbserver
#       - dbserver:
#         condition: service_healthy
#     entrypoint: wait-for-it.sh dbserver:3306 -- echo "dbserver is up"

    networks:
      - backendmysql
    restart: unless-stopped

  # -------------------- MySqlDB -------------------- #

  dbserver:
    image: mysql/mysql-server:latest
    container_name: dbserver
    environment:
      - MYSQL_DATABASE=SpeMajordb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "3308:3306"
#    healthcheck:
#            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#            timeout: 20s
#            retries: 10
    volumes:
      - /home/gopal/Desktop/SpeMajor-backend/backupdata:/var/lib/mysqldata
    networks:
      - backendmysql
    restart: unless-stopped

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - /home/gopal/Desktop/SpeMajor-backend/elastic_data:/var/lib/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'

    depends_on:
      - Backend-server

    networks:
      - backendmysql

  Logstash:
      image: logstash:7.16.2
      container_name: logstash
      restart: always
      volumes:
        - ./logstash/:/logstash_dir
      command: logstash -f /logstash.conf
      depends_on:
        - Elasticsearch
      ports:
        - '9600:9600'
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - backendmysql

  Kibana:
      image: kibana:7.16.2
      container_name: kibana
      restart: always
      ports:
        - '5601:5601'
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
        - Elasticsearch
      networks:
        - backendmysql

networks:
  backendmysql:
    driver: bridge

volumes:
  backupdata:
  elastic_data:

