---
- name: Pull docker image of the Spingboot-backend
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull coolgopalgoyal/majorprojectbackend

    - name: running container
      shell: docker run --network backend-mysql --name backend-server -p 8080:8080 -d coolgopalgoyal/majorprojectbackend
