---
- name: Pull docker image of the Spingboot-backend
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull coolgopalgoyal/majorprojectbackend

    - name: running container
      shell: docker run --name backendserver -it -d coolgopalgoyal/majorprojectbackend /bin/bash